// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Bhetbliss gift hampers packing",
  category: "Corporate gift supplier",
  address: "\n1836, opp. aksh parisar, Kumudnagar Society, Ghatlodiya, Chanakyapuri, Ahmedabad, Gujarat 380061",
  phone: "\n074057 30446",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/Bhetbliss+gift+hampers+packing/@23.074491,72.529541,17z/data=!3m1!4b1!4m6!3m5!1s0x395e830d5fdca439:0x7771145f5ce6472d!8m2!3d23.074491!4d72.529541!16s%2Fg%2F11mzh3zbs_?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.074491",
  longitude: "72.529541",
  rating: "",
  reviewsCount: "",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1780053222644_0.jpg", "/images/gmap_1780053222692_1.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Gifts from Ahmedabad's Heart",
  heroDescription: "Welcome to Bhetbliss gift hampers packing, located in the vibrant city of Ahmedabad. We specialize in crafting unique corporate gift hampers that reflect the essence of Gujarat. Our team is dedicated to providing exceptional service and ensuring your gifts are delivered with a personal touch.",
  aboutTitle: "The Story of Bhetbliss",
  aboutText: "Nestled in the charming Kumudnagar Society, our workshop at  1836, opp. aksh parisar, is where the magic happens. Our team of skilled artisans and designers come together to create one-of-a-kind gift hampers that showcase the best of Ahmedabad's culture and traditions. We take pride in our attention to detail and commitment to quality, ensuring that every gift that leaves our workshop is a testament to our passion and dedication.",
  services: [
    { icon: "🎁", title: "Customized Gift Hampers", description: "Our team will work with you to create bespoke gift hampers tailored to your company's brand and style, starting from ₹1200" },
    { icon: "📦", title: "Corporate Gift Packaging", description: "We offer a range of packaging options, from luxurious boxes to eco-friendly bags, to suit your gifting needs, priced at ₹800" },
    { icon: "👥", title: "Employee Appreciation Gifts", description: "Show your team how much you value them with our thoughtfully curated gifts, available for ₹2000" },
    { icon: "🎉", title: "Special Occasion Gifts", description: "Let us help you make your special occasions even more memorable with our custom gift hampers, starting from ₹3467" },
    { icon: "📈", title: "Bulk Gift Orders", description: "We cater to large orders, ensuring timely delivery and competitive pricing, with discounts available for orders over ₹530" },
    { icon: "📊", title: "Gift Hamper Design Services", description: "Our in-house designers will work with you to create stunning gift hampers that reflect your brand's personality, priced at ₹1500" }
  ],
  whyChooseUs: [
    { icon: "📍", title: "Strategic Location", description: "Our workshop in Ahmedabad's Chanakyapuri area allows us to serve clients across the city efficiently" },
    { icon: "💡", title: "Creative Expertise", description: "Our team of skilled artisans and designers bring a unique perspective to gift hamper creation, ensuring your gifts stand out" },
    { icon: "📦", title: "Timely Delivery", description: "We prioritize timely delivery, ensuring your gifts reach their destination on time, every time" },
    { icon: "👍", title: "Personalized Service", description: "Our dedicated customer service team is always available to address your queries and concerns" }
  ],
  testimonials: [
    { name: "Pallavi Mehta", role: "HR Manager", text: "Bhetbliss gift hampers packing has been our go-to partner for employee appreciation gifts. Their attention to detail and commitment to quality are unparalleled. We've received rave reviews from our team members about the thoughtful gifts they've received.", rating: 5 },
    { name: "Pratik Shah", role: "Marketing Manager", text: "We've been impressed with the creativity and efficiency of the Bhetbliss team. Their customized gift hampers have helped us build strong relationships with our clients and partners.", rating: 5 },
    { name: "Priyanka Deshpande", role: "Event Planner", text: "I've worked with Bhetbliss gift hampers packing on several occasions, and they've always delivered exceptional service and stunning gift hampers. Their ability to understand our vision and bring it to life is truly impressive.", rating: 5 }
  ],
  faq: { items: [{ question: "What is the minimum order quantity for customized gift hampers?", answer: "We accept orders for as few as 10 gift hampers, but prices may vary depending on the complexity of the design and the materials used." },
    { question: "Can I customize the contents of the gift hampers?", answer: "Yes, we offer a range of products and items that can be included in our gift hampers. Please contact us to discuss your specific requirements and we'll be happy to assist you." },
    { question: "Do you offer gift wrapping services?", answer: "Yes, we provide beautifully crafted gift wrapping options to complement our gift hampers. Prices start from ₹200." },
    { question: "What is the typical turnaround time for gift hamper orders?", answer: "Our standard turnaround time is 3-5 working days, but we can accommodate rush orders with prior notice and a nominal surcharge." },
    { question: "Can I cancel or change my order once it's been placed?", answer: "Please contact us as soon as possible if you need to cancel or make changes to your order. We'll do our best to accommodate your request, but please note that changes may incur additional costs or affect the delivery timeline." },
    { question: "How do I track the status of my order?", answer: "Once your order is shipped, you'll receive a tracking number via email. You can use this to track the progress of your order on our website or through the courier's website." }] },
  ctaTitle: "Elevate Your Gifting Experience",
  ctaDescription: "Discover the art of gift giving with Bhetbliss gift hampers packing. Let us help you create unforgettable gifts that leave a lasting impression.",
  ctaButtonText: "Explore Our Gifts",
  metaDescription: "Bhetbliss gift hampers packing: Expert corporate gift suppliers in Ahmedabad",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["testimonials", "faq", "services", "about", "contact", "gallery"],
  heroVariant: "image-collage",
  navStyle: "centered-nav",
  animationStyle: "scroll-triggered-reveals",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
