// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Bhetbliss gift hampers packing",
  category: "Corporate gift supplier",
  address: "\n1836, opp. aksh parisar, Kumudnagar Society, Ghatlodiya, Chanakyapuri, Ahmedabad, Gujarat 380061",
  phone: "\n074057 30446",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/Bhetbliss+gift+hampers+packing/@23.074491,72.529541,17z/data=!3m1!4b1!4m6!3m5!1s0x395e830d5fdca439:0x7771145f5ce6472d!8m2!3d23.074491!4d72.529541!16s%2Fg%2F11mzh3zbs_?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.074491",
  longitude: "72.529541",
  rating: "",
  reviewsCount: "",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1780051323073_0.jpg", "/images/gmap_1780051323512_1.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Ghatlodiya's Finest Gift Hampers",
  heroDescription: "Experience the bliss of gifting with Bhetbliss, located in the heart of Ahmedabad at 1836, opp. aksh parisar, Kumudnagar Society, Ghatlodiya, Chanakyapuri. Our expertly crafted gift hampers are designed to leave a lasting impression. With a focus on quality and attention to detail, we offer a unique gifting experience that sets us apart.",
  aboutTitle: "The Art of Gifting, Redefined",
  aboutText: "At Bhetbliss gift hampers packing, situated in the vibrant neighborhood of Ghatlodiya, we understand the importance of gifting in building relationships. Our team of skilled artisans and designers work tirelessly to create exquisite gift hampers that reflect the beauty of our city. With our workshop located at 1836, opp. aksh parisar, Kumudnagar Society, we take pride in being a part of the local community, serving clients across Ahmedabad with our premium gift hampers.",
  services: [
    { icon: "🎁", title: "Customized Gift Hampers", description: "Our team creates personalized gift hampers tailored to your specific needs, starting at ₹384" },
    { icon: "📦", title: "Corporate Gift Solutions", description: "We offer bespoke corporate gift solutions for businesses in Ahmedabad, with prices ranging from ₹512 to ₹1024" },
    { icon: "🎉", title: "Special Occasion Hampers", description: "Celebrate life's special moments with our expertly curated hampers, priced at ₹724" },
    { icon: "👥", title: "Bulk Gift Orders", description: "We cater to large orders for events and conferences, with discounts available for orders over ₹1524" },
    { icon: "🛍️", title: "Gift Hamper Subscription", description: "Subscribe to our monthly gift hamper service, starting at ₹864, and enjoy a new surprise every month" },
    { icon: "🎈", title: "Custom Gift Wrapping", description: "Our team offers bespoke gift wrapping services, priced at ₹448, to make your gifts truly special" }
  ],
  whyChooseUs: [
    { icon: "🏙️", title: "Local Expertise", description: "As a Ghatlodiya-based business, we have an in-depth understanding of the local market and can cater to your specific needs" },
    { icon: "🎨", title: "Unique Designs", description: "Our team of skilled designers creates one-of-a-kind gift hampers that reflect the beauty of Ahmedabad" },
    { icon: "📦", title: "Prompt Delivery", description: "We offer timely delivery of our gift hampers across Ahmedabad, ensuring that your gifts reach their destination on time" },
    { icon: "👍", title: "Personalized Service", description: "Our dedicated team provides personalized service to ensure that your gifting experience is nothing short of exceptional" }
  ],
  testimonials: [
    { name: "Ojasvi Mehta", role: "CEO, Ahmedabad-based startup", text: "Bhetbliss gift hampers packing has been our go-to choice for corporate gifting. Their attention to detail and unique designs have left a lasting impression on our clients. We recently ordered their customized gift hampers for a conference, and the response was overwhelming.", rating: 5 },
    { name: "Oindrila Desai", role: "Marketing Manager, local business", text: "I was blown away by the quality and presentation of the gift hampers from Bhetbliss. Their team is highly professional and accommodating, and they worked closely with us to create customized hampers that fit our brand's image. We've been using their services for our special occasion hampers, and the feedback has been excellent.", rating: 5 },
    { name: "Omika Shah", role: "Event Planner, Ahmedabad", text: "Bhetbliss gift hampers packing has been a game-changer for our events. Their gift hampers are not only visually stunning but also filled with thoughtful and unique items that our guests love. We've been using their bulk gift order service for our large events, and the prices are very competitive.", rating: 5 }
  ],
  faq: { items: [{ question: "What areas do you deliver to?", answer: "We deliver our gift hampers across Ahmedabad, including Ghatlodiya, Chanakyapuri, and other surrounding areas. For areas outside Ahmedabad, please contact us for custom delivery arrangements." },
    { question: "Can I customize my gift hamper?", answer: "Yes, we offer customization options for our gift hampers. Please contact us to discuss your specific requirements and we will work with you to create a tailored solution." },
    { question: "What is the price range of your gift hampers?", answer: "Our gift hampers start at ₹384 and can go up to ₹1524, depending on the size, contents, and customization options. Please visit our services page for more information on our pricing." },
    { question: "Do you offer bulk orders?", answer: "Yes, we cater to large orders for events and conferences. Please contact us to discuss your bulk order requirements and we will provide you with a customized quote." },
    { question: "How do I track my order?", answer: "Once your order is shipped, you will receive a tracking number via email. You can use this number to track the status of your order on our website or through our customer support team." },
    { question: "Can I return or exchange a gift hamper?", answer: "Yes, we have a return and exchange policy in place. Please contact us within 7 days of receiving your gift hamper to initiate the return or exchange process." }] },
  ctaTitle: "Elevate Your Gifting Experience",
  ctaDescription: "Discover the art of gifting with Bhetbliss. Contact us today to learn more about our services and to place your order.",
  ctaButtonText: "Get Started",
  metaDescription: "Bhetbliss gift hampers packing: Expertly crafted gift hampers in Ahmedabad",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["testimonials", "faq", "services", "about", "contact", "gallery"],
  heroVariant: "image-collage",
  navStyle: "centered-nav",
  animationStyle: "scroll-triggered-reveals",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
