// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Bhetbliss gift hampers packing",
  category: "Corporate gift supplier",
  address: "\n1836, opp. aksh parisar, Kumudnagar Society, Ghatlodiya, Chanakyapuri, Ahmedabad, Gujarat 380061",
  phone: "\n074057 30446",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/Bhetbliss+gift+hampers+packing/@23.074491,72.529541,17z/data=!3m1!4b1!4m6!3m5!1s0x395e830d5fdca439:0x7771145f5ce6472d!8m2!3d23.074491!4d72.529541!16s%2Fg%2F11mzh3zbs_?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.074491",
  longitude: "72.529541",
  rating: "",
  reviewsCount: "",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1780055954580_0.jpg", "/images/gmap_1780055954632_1.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Gifts from Ahmedabad's Heart",
  heroDescription: "Bhetbliss gift hampers packing offers bespoke corporate gifts, carefully crafted in the heart of Ahmedabad. Located at  1836, opp. aksh parisar, Kumudnagar Society, Ghatlodiya, Chanakyapuri, our team creates unique gift hampers that reflect your brand's essence. With a focus on quality and attention to detail, we help you build lasting relationships with your clients and employees.",
  aboutTitle: "Our Story Unfolds",
  aboutText: "Nestled in the bustling streets of Ghatlodiya, Ahmedabad, Bhetbliss gift hampers packing has been perfecting the art of corporate gifting since its inception. Our team, based at  1836, takes pride in creating personalized gifts that cater to the diverse needs of our clients. With a deep understanding of the local culture and a passion for innovation, we strive to make every gift a memorable experience.",
  services: [
    { icon: "🎁", title: "Customized Gift Hampers", description: "Tailor-made gift hampers starting from ₹442, designed to fit your brand's unique identity and budget." },
    { icon: "📦", title: "Corporate Gift Packaging", description: "Elegant packaging solutions for your corporate gifts, priced between ₹815 and ₹1223, ensuring a lasting impression on your clients and employees." },
    { icon: "📈", title: "Bulk Gift Orders", description: "Discounted rates for bulk orders, starting from ₹2549 for 10 gifts, making it easy to manage your corporate gifting needs." },
    { icon: "👥", title: "Employee Recognition Gifts", description: "Thoughtful gifts for your employees, starting from ₹699, to appreciate their hard work and dedication, fostering a positive work environment." },
    { icon: "📊", title: "Budget-Friendly Options", description: "Affordable gift options, priced between ₹1098 and ₹2115, without compromising on quality, ensuring that you stay within your budget." },
    { icon: "🎉", title: "Anniversary and Event Gifts", description: "Special occasion gifts, starting from ₹1553, to mark important milestones and events, leaving a lasting impression on your clients and partners." }
  ],
  whyChooseUs: [
    { icon: "📍", title: "Strategic Location", description: "Our location in Ghatlodiya, Ahmedabad, allows us to cater to a wide range of clients across the city, ensuring timely delivery and prompt service." },
    { icon: "🎨", title: "Creative Expertise", description: "Our team of skilled designers and craftsmen bring a unique perspective to corporate gifting, creating one-of-a-kind gifts that reflect your brand's personality." },
    { icon: "📈", title: "Competitive Pricing", description: "We offer competitive pricing, starting from ₹442, without compromising on the quality of our gifts, ensuring that you get the best value for your money." },
    { icon: "📦", title: "Reliable Logistics", description: "Our robust logistics network ensures that your gifts are delivered on time, every time, across Ahmedabad and beyond." }
  ],
  testimonials: [
    { name: "Gitanjali Mehta", role: "HR Manager", text: "Bhetbliss gift hampers packing has been our go-to corporate gift supplier for the past year. Their attention to detail and prompt service have made a significant impact on our employee recognition programs. We appreciate the customized gift hampers they provide, which start from ₹442 and fit our budget perfectly.", rating: 5 },
    { name: "Gaurav Patel", role: "Marketing Manager", text: "The team at Bhetbliss gift hampers packing has been instrumental in helping us create memorable corporate gifts for our clients. Their bulk order discounts, starting from ₹2549 for 10 gifts, have been a game-changer for our business. We look forward to continuing our partnership with them.", rating: 5 },
    { name: "Gunjan Desai", role: "CEO", text: "We've been impressed with the quality and creativity of Bhetbliss gift hampers packing's corporate gifts. Their budget-friendly options, priced between ₹1098 and ₹2115, have allowed us to stay within our budget while still making a lasting impression on our clients. We highly recommend them for all your corporate gifting needs.", rating: 5 }
  ],
  faq: { items: [{ question: "What is the minimum order quantity for customized gift hampers?", answer: "The minimum order quantity for customized gift hampers is 5, with prices starting from ₹699 per gift." },
    { question: "Do you offer discounts for bulk orders?", answer: "Yes, we offer discounts for bulk orders, starting from ₹2549 for 10 gifts. Please contact us for more information on our bulk order pricing." },
    { question: "What is the average delivery time for gifts?", answer: "The average delivery time for gifts is 3-5 working days within Ahmedabad and 7-10 working days for outside Ahmedabad." },
    { question: "Can I customize the gifts according to my brand's requirements?", answer: "Yes, we offer customized gift options, starting from ₹815, where you can choose the packaging, contents, and design to fit your brand's unique identity." },
    { question: "What is the price range of your corporate gifts?", answer: "Our corporate gifts are priced between ₹442 and ₹3639, depending on the type and quantity of gifts. Please contact us for more information on our pricing and packages." },
    { question: "Do you have a physical store where I can visit and explore your gift options?", answer: "Yes, you can visit our store located at  1836, opp. aksh parisar, Kumudnagar Society, Ghatlodiya, Chanakyapuri, Ahmedabad, to explore our gift options and discuss your corporate gifting needs with our team." }] },
  ctaTitle: "Elevate Your Corporate Gifting",
  ctaDescription: "Get in touch with us to discover how our customized gift hampers can enhance your brand's reputation and build lasting relationships with your clients and employees.",
  ctaButtonText: "Explore Gifts",
  metaDescription: "Bhetbliss gift hampers packing: Expert corporate gift suppliers in Ahmedabad, offering customized gift hampers starting from ₹442.",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["testimonials", "faq", "services", "about", "contact", "gallery"],
  heroVariant: "image-collage",
  navStyle: "centered-nav",
  animationStyle: "scroll-triggered-reveals",
  cardStyle: "rounded-xl bg-gradient-to-br from-card to-transparent",
  darkMode: false,
};
